### PR TITLE
Feature: Customization of various file paths

### PR DESCRIPTION
**Pull request by mpaupulaire4**
## Overview
In my use cases I run the process from different subdirectories of a project and have it installed globally as well as a dependency to a project. These changes will allow someone to customize whether files are saved or loaded relative to the scenario file (the only exception being a parser method file which is always loaded relative to the scenario file) and allow for more powerful use in npm scripts and aliasing.

## Changes
* Added the `relativeTo` key to `entity`, `template`, and 'use'
  * The key can either be 'process' or 'scenario' for loading relative to the process or the scenario file respectively. It defaults to 'scenario' for backwards compatability
  * When set in 'entity' and 'template' it affects where the file is loaded and when set in 'use' it affects where the generated file is saved
* Added the option `--base-dir <path/to/directory>`
  * This affects where scenario files are searched for. `mtml --base-dir ../path/to/dir scenario.mtml` is equivalent to `mtml ../path/to/dir/scenario.mtml`. 
  * Use Case: with a directory `mtml/` in my project root containing a scenario 'component' and templates. I can create an npm script `create: mtml --base-dir ./mtml` and run `yarn create component user.json`

### CODE REVIEW

**Comment by dchrzanowski** [comment]
This is very neat. I'll review and merge after work.

**Comment by mpaupulaire4** [comment]
I thought about moving the `--base-dir` option to a config file. So that mtml looks for something like a .mtml.config file and removes the need for the option on the command line. What do you think @dchrzanowski?

**Comment by mpaupulaire4** [comment]
I also want to update the docs

**Comment by dchrzanowski** [comment]
@mpaupulaire4 I think that entering it from the command line is absolutely fine. Down the line, if the amount of features will get out of control then perhaps a config file would be a good option. For the time being there is only 2, with your addition that would be 3. Not a bad idea though!!!

**Comment by dchrzanowski** [comment]
@mpaupulaire4 For the time being I do not understand the reasoning of `--base-dir`. Calling `mtml ../foo/bar/scenario.mtml` would be the same as `mtml --base-dir ../foo/bar scenario.mtml`. What is the benefit?

**Comment by dchrzanowski** [comment]
I personally do not like the idea of `relativeTo` key as compulsory. I'd take it on as optional, keep it simple.

**Comment by mpaupulaire4** [comment]
@dchrzanowski  the `relativeTo` key is optional. It is left undefined it will default to `"scenario"`.

It is hard to see the benefit of the `--base-dir` option when using it purely from the command line. I have an alias for mtml globally and a script that leverages it in my package.json. This way my script can be defined as `make: mtml --base-dir mtml/` and I can run `yarn create component data.json`, since the rest of the arguments are piped in.

**Comment by dchrzanowski** [comment]
Thanks for changing the `relativeTo` key to optional.

Ok, so the benefit of having `--base-dir` is that you don't have to write the full path to the scenario file every time, basically. It would be the equivalent of creating an alias that would end with a path slash.

I get you now. I might get a chance to review this, this evening.

**Comment by dchrzanowski** [comment]
@mpaupulaire4 Thank you very much for your fantastic work. At first I couldn't (somehow) wrap my head around the changes, but it just makes so much sense. The only thing I did really is change the `process` to `cwd`. Just thought it was more adequate. Once again,.thanks for the PR!

**Pull request merged**
