### PR TITLE
feat(parserEval)

### LINKED ISSUE #5: parser data doesn't seem to accept h.getArg
Hi,

I'm trying to use the entity parser. When I provide h.getArg(1) to the data key of the parser it doesn't seem to work and returns `File read error: Error: ENOENT: no such file or directory, open '/projects/private/packages/style-atoms/h.getArg(1)'` with this entity configuration:
```
{
  "entity": {
    "parser": {
      "file": "./scripts/dimensionParser",
      "data": "h.getArg(1)"
    }
}
```
is the data key not parsed by mtml?

### PR DESCRIPTION
**Pull request by belgac**
this allows to eval the keys of the parser config.

fix #5

### CODE REVIEW

**Comment by dchrzanowski** [comment]
I'm so sorry @belgac I've already published the fixed version before I noticed this PR. My sincere apologies!

**Comment by belgac** [comment]
no problem, thank you for your reactivity ;)

**Comment by dchrzanowski** [comment]
Just got home from work, :-)

**Comment by dchrzanowski** [comment]
Just got home :smile:

**Pull request closed without merging**
