### PR TITLE
feature: use condition

### PR DESCRIPTION
**Pull request by belgac**
First of all thank you a lot for your project it's exactly what i was searching for.

In my personal use case I need to be able to conditionnaly generate some files.

For this purpose I created a new key in the use object called `condition`:
- if the key is not there or if the key is there and evals to true  this use object is executed
- if the key is there and evals to false or the evals fails this use object is not executed

I also refactored you evalOrLeave helper to create a evalOr helper that i use for evalOrLeave and evalOr false.

### CODE REVIEW

**Comment by mpaupulaire4** [comment]
@belgac I would also edit the README to document the change

**Review by mpaupulaire4 — APPROVED** [review]

**Review by mpaupulaire4 — CHANGES_REQUESTED** [review]
@belgac I would edit the README to document the new feature

**Comment by belgac** [comment]
OK i will add the readme documentation soon. 

In the meantime I tought about my implementation, I think the behavior should be:

- if the key is not there or if the key is there and evals to true this use object is executed
- if the key is there and evals to false this use object is not executed
- if the key is there and the evals fails mtml should throw with the abort helper

I will push this changes right now and work on the readme this weekend

**Comment by dchrzanowski** [comment]
I'll review this after I'll come back from work. Great idea though!!!

**Comment by dchrzanowski** [comment]
I'm going to accept it. but I'll have to rework it anyway. I don't like the convoluted obfuscation that currently exists in the eval functions. Side note, absolutely never add windows end of line characters. It seems that you auto-formatted the file, big no-no.

**Comment by dchrzanowski** [comment]
I've just pushed slightly reworked version of what you have proposed. I took the liberty of renaming 'condition' to simply 'if'

**Comment by belgac** [comment]
thank you a lot! 
the if name is way better (and gives me a lot of other ideas).

Sorry for the line endings i'm just so used of starting my projects with this .gitattributes (https://github.com/alexkaratarakis/gitattributes/blob/master/Web.gitattributes) that auto-fix it that I forget it's not in every project :/

**Pull request merged**
